<a href="https://colab.research.google.com/github/DebugWithNazi/Machine-Learning-Course/blob/main/Machine_Learning_lecture2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**What are Tensors?**

    -> a data structure

    -> a container for numbers

    -> zero-dimention is scalar, list of numbers called a vector, rows and columns called 2 dimention and so on, so these all are tensors

**0-d tensor/scalar:**
if we store single number, its called 0-d tensor or scalar.

[8], [10] are 0-d tensors

( n-dimensional array is actually called tensor )

**1-D tensor/ vector / 1-D array:** like [1,2,3,4,5]

**note:** now axis means dimensions, no. of axis is also called rank sometimes


In [ ]:
import numpy as np

arr0d = np.array(43)
print(arr0d.ndim)

arr1d = np.array([1,2,3,4]) # now this is one-d tensor but it is 4-d vector, why? bcz this vector have 4 elements in it
print(arr1d.ndim)



0
1


**2-d tensors/matrics:** matrices are nothing, but collections of vectors (in rows and columns)


In [ ]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Note:**

     -> no. of axis = rank = no. of dimentions

     -> shape = how many items in particular axis, like 2 elements in rows and 3 elements in columns

     -> Size of a tensor = multiply shape elements (shape = (3*2) then size = 6, means 6 elements will store in this tensor)


Examples:

1-D tensor → Just a simple list of numbers. Shape: (5)
Example: [1, 2, 3, 4, 5]

2-D tensor → Like a matrix (rows × columns). Shape: (2, 3)
Example: [[1, 2, 3], [3, 4, 5]]

3-D tensor → A stack of matrices. Shape: (2, 2, 3)
Example: [[[1, 2, 3], [3, 4, 5]], [[3, 4, 5], [6, 7, 8]]]

4-D tensor → Often used for image batches. Shape example: (5, 3, 4, 4)

5 → number of images

3 → channels (e.g., RGB)

4 × 4 → height × width

5-D tensor → Often used for video batches. Shape example: (400, 2, 45, 5, 6)

400 → number of videos

2 → channels (e.g., grayscale or RGB split into 2)

45 → frames per video

5 × 6 → frame height × frame width